### ISSUE TITLE
Remove 'Get it on Google Play button'

### ISSUE THREAD

**Issue by OMIsie11** [dmitriy-chernysh/covid-19-tracker-android#29]
Hi,  
I found this repo accidentally and saw "Get it on Google Play" button.  
I think You shouldn't use that button because link is not pointing to Google Play. I would watch out, because it's against the rules and that repo could get blocked.

**Comment by dmitriy-chernysh** [comment]
Hi Oskar! Thanks for the issue. You are right.

**Comment by dmitriy-chernysh** [comment]
Done
